FROM chenhw2/alpine:base
LABEL MAINTAINER="https://github.com/honwen"

# /usr/bin/sing-box /data/geo*.db
RUN cd /tmp \
  && curl -skSLO $( \
  curl -skSL 'https://api.github.com/repos/kyochikuto/sing-box-plus/releases/latest' | \
  yq -r '.assets[]|.browser_download_url' | grep 'linux-amd64.zip$' \
  ) \
  && unzip sing-box-*-linux-amd64.zip -d /usr/bin/ \
  && sing-box version \
  && rm -rf /tmp/* /usr/bin/LICENSE

CMD ["sing-box", "run", "-c", "/opt/config.json"]

