# refs:https://github.com/nicolasff/docker-cassandra/issues/8
user=dnsmasq
no-resolv
no-hosts
all-servers
conf-dir=/etc/dnsmasq.d/,*.conf
# log-facility=/var/log/dnsmasq.log
log-facility=-
log-queries
log-debug

server=127.0.0.1#7900

# For Mirrors
server=/edu.cn/223.5.5.5
server=/edu.cn/114.114.115.115
server=/aliyun.com/223.5.5.5
server=/aliyun.com/114.114.115.115
server=/tencent.com/119.29.29.29
server=/tencent.com/114.114.115.115
server=/huaweicloud.com/223.5.5.5
server=/huaweicloud.com/114.114.115.115

# For wuyou
server=/wuyou.net/223.5.5.5
server=/wuyou.net/119.29.29.29
server=/wuyou.net/114.114.115.115

# For CDNs
server=/githubusercontents.com/223.5.5.5
server=/githubusercontents.com/119.29.29.29
server=/githubusercontents.com/114.114.115.115
server=/staticfile.org/223.5.5.5
server=/staticfile.org/119.29.29.29
server=/fastgit.org/223.5.5.5
server=/fastgit.org/119.29.29.29
server=/fastgit.org/114.114.115.115
server=/cnpmjs.org/223.5.5.5
server=/cnpmjs.org/119.29.29.29
server=/cnpmjs.org/114.114.115.115

# For ADs
address=/firefoxchina.cn/
address=/hao.centbrowser.cn/
address=/lb2345.com/
address=/example.com/

# For PCDN
address=/szbdyd.com/
address=/mcdn.bilivideo.cn/
address=/snodehome.com/
address=/snodehome.cn/
address=/v.smtcdns.net/
address=/chat.bilibili.com/
address=/ppio.cloud/
address=/p2p.huya.com/
address=/pp.io/
address=/stun.douyucdn.cn/
address=/p2perrorlog.douyucdn.cn/
address=/stun1.douyucdn.cn/
address=/dyp2p-hw.douyucdn.cn/
address=/stun-h5.qvb.qcloud.com/
address=/tracker-00.qvb.qcloud.com/
address=/flux.hcdn.71edge.com/
address=/web-player-tracker.biliapi.net/
address=/hw-web-player-tracker.biliapi.net/
address=/stun.hitv.com/
address=/cdn.steampipe.steamcontent.com/
address=/steampipe.akamaized.net/
address=/steamcontent.com/
address=/steamcdn-a.akamaihd.net/

# For trackers
address=/config.cmpassport.com/
address=/www.cmpassport.com/
address=/wap.cmpassport.com/
address=/onekey1.cmpassport.com/
address=/log1.cmpassport.com/
address=/smsks1.cmpassport.com/
address=/verify.cmpassport.com/
address=/opencloud.wostore.cn/
address=/auth.wosms.cn/
address=/id.mail.wo.cn/
address=/mdn.open.wo.cn/
address=/hmrz.wo.cn/
address=/nishub1.10010.com/
address=/enrichgw.10010.com/
address=/id6.me/
address=/open.e.189.cn/
address=/ye.dun.163yun.com/
address=/amplitude.com/
address=/branch.io/
address=/applovin.com/
address=/applvn.com/
address=/bluekai.com/
address=/chartboost.com/
address=/flurry.com/
address=/fitanalytics.com/
address=/analytics.localytics.com/
address=/mob.com/
address=/mtrtb.com/
address=/newrelic.com/
address=/nr-data.net/
address=/play.googleapis.com/
address=/plugco.in/
address=/scarabresearch.com/
address=/sdk.foursquare.com/
address=/umeng.com/
address=/umengcloud.com/
address=/voicefive.com/
address=/segment.io/
address=/api.myendpoint.io/
address=/smart-sense.org/
address=/eum-appdynamics.com/
address=/sentry.io/
