# refs:https://github.com/nicolasff/docker-cassandra/issues/8
user=dnsmasq
no-resolv
no-hosts
all-servers
conf-dir=/etc/dnsmasq.d/,*.conf
# log-facility=/var/log/dnsmasq.log
log-facility=-
log-queries
log-debug

server=127.0.0.1#7900
# For Mirrors
server=/edu.cn/127.0.0.1#7701
server=/edu.cn/223.5.5.5
server=/edu.cn/114.114.115.115
server=/ctyun.cn/127.0.0.1#7701
server=/ctyun.cn/223.5.5.5
server=/ctyun.cn/114.114.115.115
server=/cmecloud.cn/127.0.0.1#7701
server=/cmecloud.cn/223.5.5.5
server=/cmecloud.cn/114.114.115.115
server=/aliyun.com/127.0.0.1#7701
server=/aliyun.com/223.5.5.5
server=/aliyun.com/114.114.115.115
server=/volces.com/127.0.0.1#7701
server=/volces.com/180.184.1.1
server=/volces.com/114.114.115.115
server=/tencent.com/127.0.0.1#7701
server=/tencent.com/119.29.29.29
server=/tencent.com/114.114.115.115
server=/huaweicloud.com/127.0.0.1#7701
server=/huaweicloud.com/223.5.5.5
server=/huaweicloud.com/114.114.115.115

# For ADs
address=/firefoxchina.cn/
address=/hao.centbrowser.cn/
address=/lb2345.com/
address=/example.com/

# For PCDN
address=/bsccdn.net/
address=/cdn.steampipe.steamcontent.com/
address=/chat.bilibili.com/
address=/dyp2p-ali.douyucdn.cn/
address=/dyp2p-hw.douyucdn.cn/
address=/flux.hcdn.71edge.com/
address=/gjfzpt.cn/
address=/hw-web-player-tracker.biliapi.net/
address=/jomodns.cn/
address=/jwbwc.cn/
address=/kuiniuca.com/
address=/mcdn.bilivideo.cn/
address=/onethingpcs.com/
address=/p2p-ali.douyucdn.cn/
address=/p2pchunk-hw.douyucdn.cn/
address=/p2pchunk-table.douyucdn.cn/
address=/p2pchunk-ws.douyucdn.cn/
address=/p2perrorlog.douyucdn.cn/
address=/p2p.huya.com/
address=/p2plive-ali.douyucdn.cn/
address=/p2plive-ws.douyucdn.cn/
address=/p2plog.douyucdn.cn/
address=/p2p.qq.com/
address=/p2ptun.qq.com/
address=/p2pupdate.gamedl.qq.com/
address=/p2pupgrade.gamedl.qq.com/
address=/p2pvod-ws.douyucdn.cn/
address=/pcdn.xmcdn.com/
address=/pcdn.yximgs.com/
address=/pkoplink.com/
address=/pp.io/
address=/ppio.cloud/
address=/saxysec.com/
address=/smogfly.cloud/
address=/smogflycloud.com/
address=/smogfly.club/
address=/smogfly.cn/
address=/smogfly.com.cn/
address=/smogfly.net/
address=/snodehome.cn/
address=/snodehome.com/
address=/steamcdn-a.akamaihd.net/
address=/steamcontent.com/
address=/steampipe.akamaized.net/
address=/stun1.douyucdn.cn/
address=/stun.douyucdn.cn/
address=/stun-h5.qvb.qcloud.com/
address=/stun.hitv.com/
address=/szbdyd.com/
address=/tpa-hcdn.iqiyi.com/
address=/tracker-00.qvb.qcloud.com/
address=/uhabo.com/
address=/v.smtcdns.net/
address=/web-player-tracker.biliapi.net/
address=/wuchucloud.cn/
address=/wuchucloud.com/
address=/wuchucloud.net/
address=/wuchuyun.com/
address=/wuchuyun.net/
address=/xycdn.com/


# For trackers
address=/config.cmpassport.com/
address=/www.cmpassport.com/
address=/wap.cmpassport.com/
address=/onekey1.cmpassport.com/
address=/log1.cmpassport.com/
address=/smsks1.cmpassport.com/
address=/verify.cmpassport.com/
address=/opencloud.wostore.cn/
address=/auth.wosms.cn/
address=/id.mail.wo.cn/
address=/mdn.open.wo.cn/
address=/hmrz.wo.cn/
address=/nishub1.10010.com/
address=/enrichgw.10010.com/
address=/id6.me/
address=/open.e.189.cn/
address=/ye.dun.163yun.com/
address=/amplitude.com/
address=/branch.io/
address=/applovin.com/
address=/applvn.com/
address=/bluekai.com/
address=/chartboost.com/
address=/flurry.com/
address=/fitanalytics.com/
address=/analytics.localytics.com/
address=/mob.com/
address=/mtrtb.com/
address=/newrelic.com/
address=/nr-data.net/
address=/play.googleapis.com/
address=/plugco.in/
address=/scarabresearch.com/
address=/sdk.foursquare.com/
address=/umeng.com/
address=/umengcloud.com/
address=/voicefive.com/
address=/segment.io/
address=/api.myendpoint.io/
address=/smart-sense.org/
address=/eum-appdynamics.com/
address=/sentry.io/
